// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package daemon

import (
	"easyslip.cc/mic-project-layout/internal/app/daemon/internal/daemon"
	"easyslip.cc/mic-project-layout/internal/boot"
	"github.com/qmute/mic/v4"
)

// Injectors from wire.go:

func New() (*App, func(), error) {
	bootloader := boot.Bootloader{}
	initializer := &daemon.Initializer{}
	daemonBootloader := &Bootloader{
		Bootloader: bootloader,
		Daemon:     initializer,
	}
	config, err := mic.DefaultConfig()
	if err != nil {
		return nil, nil, err
	}
	opt := defaultMicDaemonOpt(config)
	service, cleanup, err := mic.DefaultService(opt)
	if err != nil {
		return nil, nil, err
	}
	webOpt := defaultMicWebDaemonOpt(config, service)
	webService := mic.DefaultWeb(webOpt)
	app := &App{
		Bootloader:      daemonBootloader,
		MicroWebService: webService,
		Service:         service,
	}
	return app, func() {
		cleanup()
	}, nil
}
