// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serve

import (
	"github.com/qmute/mic-project-layout/internal/app/serve/admin"
	hdl2 "github.com/qmute/mic-project-layout/internal/app/serve/admin/hdl"
	mid2 "github.com/qmute/mic-project-layout/internal/app/serve/admin/hdl/mid"
	"github.com/qmute/mic-project-layout/internal/app/serve/front"
	"github.com/qmute/mic-project-layout/internal/app/serve/front/hdl"
	"github.com/qmute/mic-project-layout/internal/app/serve/front/hdl/mid"
	"github.com/qmute/mic-project-layout/internal/boot"
	"github.com/qmute/mic-project-layout/internal/config"
	"github.com/qmute/mic/v4"
)

// Injectors from wire.go:

func New() (*App, func(), error) {
	bootloader := boot.Bootloader{}
	serveBootloader := &Bootloader{
		Bootloader: bootloader,
	}
	configConfig, err := mic.DefaultConfig()
	if err != nil {
		return nil, nil, err
	}
	opt := defaultMicOpt(configConfig)
	service, cleanup, err := mic.DefaultService(opt)
	if err != nil {
		return nil, nil, err
	}
	webOpt := defaultMicWebOpt(configConfig, service)
	webService := mic.DefaultWeb(webOpt)
	path := boot.GetConfigPath(configConfig)
	config2, err := config.New(path)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clientMid := &mid.ClientMid{}
	midMid := &mid.Mid{
		ClientMid: clientMid,
	}
	base := hdl.Base{}
	pubHdl := &hdl.PubHdl{
		Base: base,
	}
	hdlHdl := &hdl.Hdl{
		Mid:    midMid,
		PubHdl: pubHdl,
	}
	app := &front.App{
		Hdl: hdlHdl,
	}
	mid3 := &mid2.Mid{}
	hdlBase := hdl2.Base{}
	hdlPubHdl := &hdl2.PubHdl{
		Base: hdlBase,
	}
	hdl3 := &hdl2.Hdl{
		Mid: mid3,
		Pub: hdlPubHdl,
	}
	adminApp := &admin.App{
		Hdl: hdl3,
	}
	web := &Web{
		Config: config2,
		Front:  app,
		Admin:  adminApp,
	}
	serveApp := &App{
		Bootloader:      serveBootloader,
		MicroWebService: webService,
		Service:         service,
		Web:             web,
	}
	return serveApp, func() {
		cleanup()
	}, nil
}
